# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ewd.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

#from test import dateCheck
from .database import saveInfo,find_employee,updateInfo,generate_report,gen,dateCheck

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1038, 808)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 993, 1172))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setMinimumSize(QtCore.QSize(1, 1150))
        self.widget.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.149254 rgba(7, 82, 42, 145), stop:0.427861 rgba(112, 196, 164, 97), stop:0.736318 rgba(0, 0, 0, 60));")
        self.widget.setObjectName("widget")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setGeometry(QtCore.QRect(60, 60, 861, 1031))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setStyleSheet("font: 11pt \"Arial Rounded MT Bold\";\n"
"background-color: rgb(255, 255, 255);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Reports = QtWidgets.QWidget()
        self.Reports.setObjectName("Reports")
        self.title = QtWidgets.QLineEdit(self.Reports)
        self.title.setGeometry(QtCore.QRect(120, 140, 611, 41))
        self.title.setDragEnabled(True)
        self.title.setClearButtonEnabled(True)
        self.title.setObjectName("title")
        self.spacing = QtWidgets.QLineEdit(self.Reports)
        self.spacing.setGeometry(QtCore.QRect(120, 410, 621, 41))
        self.spacing.setDragEnabled(True)
        self.spacing.setClearButtonEnabled(True)
        self.spacing.setObjectName("spacing")
        self.ffrom = QtWidgets.QDateEdit(self.Reports)
        self.ffrom.setGeometry(QtCore.QRect(210, 220, 521, 41))
        self.ffrom.setSpecialValueText("")
        self.ffrom.setObjectName("ffrom")
        self.label = QtWidgets.QLabel(self.Reports)
        self.label.setGeometry(QtCore.QRect(120, 220, 71, 41))
        self.label.setStyleSheet("\n"
"font: 16pt \"Berlin Sans FB\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Reports)
        self.label_2.setGeometry(QtCore.QRect(120, 330, 61, 41))
        self.label_2.setStyleSheet("\n"
"font: 16pt \"Berlin Sans FB\";")
        self.label_2.setObjectName("label_2")
        self.to = QtWidgets.QDateEdit(self.Reports)
        self.to.setGeometry(QtCore.QRect(210, 330, 521, 41))
        self.to.setSpecialValueText("")
        self.to.setObjectName("to")
        self.saveButton = QtWidgets.QPushButton(self.Reports)
        self.saveButton.setGeometry(QtCore.QRect(80, 550, 271, 51))
        self.saveButton.setStyleSheet("background-color: rgb(0, 71, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;")
        self.saveButton.setObjectName("saveButton")
        self.openButton = QtWidgets.QPushButton(self.Reports)
        self.openButton.setGeometry(QtCore.QRect(430, 550, 301, 51))
        self.openButton.setStyleSheet("background-color: rgb(0, 0, 118);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;")
        self.openButton.setObjectName("openButton")
        self.line = QtWidgets.QFrame(self.Reports)
        self.line.setGeometry(QtCore.QRect(20, 520, 811, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.Reports)
        self.line_2.setGeometry(QtCore.QRect(70, 90, 721, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.Reports)
        self.line_3.setGeometry(QtCore.QRect(20, 620, 811, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.Reports)
        self.line_4.setGeometry(QtCore.QRect(70, 20, 721, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_3 = QtWidgets.QLabel(self.Reports)
        self.label_3.setGeometry(QtCore.QRect(100, 40, 301, 41))
        self.label_3.setStyleSheet("\n"
"font: 16pt \"Berlin Sans FB\";")
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.Reports, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.line_5 = QtWidgets.QFrame(self.tab_2)
        self.line_5.setGeometry(QtCore.QRect(80, 10, 721, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.tab_2)
        self.line_6.setGeometry(QtCore.QRect(80, 60, 721, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(100, 20, 301, 40))
        self.label_4.setStyleSheet("\n"
"font: 16pt \"Berlin Sans FB\";")
        self.label_4.setObjectName("label_4")
        self.kim = QtWidgets.QLineEdit(self.tab_2)
        self.kim.setGeometry(QtCore.QRect(80, 100, 661, 41))
        self.kim.setDragEnabled(True)
        self.kim.setClearButtonEnabled(True)
        self.kim.setObjectName("kim")
        self.lname = QtWidgets.QLineEdit(self.tab_2)
        self.lname.setGeometry(QtCore.QRect(80, 280, 661, 41))
        self.lname.setDragEnabled(True)
        self.lname.setClearButtonEnabled(True)
        self.lname.setObjectName("lname")
        self.fname = QtWidgets.QLineEdit(self.tab_2)
        self.fname.setGeometry(QtCore.QRect(80, 220, 661, 41))
        self.fname.setDragEnabled(True)
        self.fname.setClearButtonEnabled(True)
        self.fname.setObjectName("fname")
        self.gender = QtWidgets.QComboBox(self.tab_2)
        self.gender.setGeometry(QtCore.QRect(82, 160, 661, 41))
        self.gender.setObjectName("gender")
        self.gender.addItem("")
        self.gender.addItem("")
        self.gender.addItem("")
        self.employee_group = QtWidgets.QLineEdit(self.tab_2)
        self.employee_group.setGeometry(QtCore.QRect(80, 520, 661, 41))
        self.employee_group.setDragEnabled(True)
        self.employee_group.setClearButtonEnabled(True)
        self.employee_group.setObjectName("employee_group")
        self.personal_number = QtWidgets.QLineEdit(self.tab_2)
        self.personal_number.setGeometry(QtCore.QRect(80, 460, 661, 41))
        self.personal_number.setDragEnabled(True)
        self.personal_number.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.personal_number.setClearButtonEnabled(True)
        self.personal_number.setObjectName("personal_number")
        self.birthday = QtWidgets.QDateEdit(self.tab_2)
        self.birthday.setGeometry(QtCore.QRect(260, 350, 481, 31))
        self.birthday.setSpecialValueText("")
        self.birthday.setObjectName("birthday")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(90, 350, 111, 31))
        self.label_5.setStyleSheet("\n"
"font: 14pt \"Berlin Sans FB\";")
        self.label_5.setObjectName("label_5")
        self.date_of_entry = QtWidgets.QDateEdit(self.tab_2)
        self.date_of_entry.setGeometry(QtCore.QRect(260, 410, 481, 31))
        self.date_of_entry.setSpecialValueText("")
        self.date_of_entry.setObjectName("date_of_entry")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(90, 410, 161, 31))
        self.label_6.setStyleSheet("\n"
"font: 14pt \"Berlin Sans FB\";")
        self.label_6.setObjectName("label_6")
        self.report = QtWidgets.QLineEdit(self.tab_2)
        self.report.setGeometry(QtCore.QRect(80, 760, 661, 41))
        self.report.setDragEnabled(True)
        self.report.setClearButtonEnabled(True)
        self.report.setObjectName("report")
        self.email = QtWidgets.QLineEdit(self.tab_2)
        self.email.setGeometry(QtCore.QRect(80, 700, 661, 41))
        self.email.setDragEnabled(True)
        self.email.setClearButtonEnabled(True)
        self.email.setObjectName("email")
        self.employement_type = QtWidgets.QLineEdit(self.tab_2)
        self.employement_type.setGeometry(QtCore.QRect(80, 640, 661, 41))
        self.employement_type.setDragEnabled(True)
        self.employement_type.setClearButtonEnabled(True)
        self.employement_type.setObjectName("employement_type")
        self.hr_level = QtWidgets.QLineEdit(self.tab_2)
        self.hr_level.setGeometry(QtCore.QRect(80, 580, 661, 41))
        self.hr_level.setDragEnabled(True)
        self.hr_level.setClearButtonEnabled(True)
        self.hr_level.setObjectName("hr_level")
        self.current_position = QtWidgets.QLineEdit(self.tab_2)
        self.current_position.setGeometry(QtCore.QRect(80, 820, 661, 41))
        self.current_position.setDragEnabled(True)
        self.current_position.setClearButtonEnabled(True)
        self.current_position.setObjectName("current_position")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 910, 271, 51))
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 71, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;")
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(440, 910, 271, 51))
        self.pushButton_4.setStyleSheet("background-color: rgb(0, 0, 118);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;")
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.line_9 = QtWidgets.QFrame(self.tab_2)
        self.line_9.setGeometry(QtCore.QRect(50, 880, 721, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.tab_2)
        self.line_10.setGeometry(QtCore.QRect(50, 970, 721, 16))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.line_7 = QtWidgets.QFrame(self.tab)
        self.line_7.setGeometry(QtCore.QRect(40, 20, 721, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.tab)
        self.line_8.setGeometry(QtCore.QRect(40, 70, 721, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(60, 30, 301, 40))
        self.label_7.setStyleSheet("\n"
"font: 16pt \"Berlin Sans FB\";")
        self.label_7.setObjectName("label_7")
        self.kim_2 = QtWidgets.QLineEdit(self.tab)
        self.kim_2.setGeometry(QtCore.QRect(70, 110, 661, 41))
        self.kim_2.setDragEnabled(True)
        self.kim_2.setClearButtonEnabled(True)
        self.kim_2.setObjectName("kim_2")
        self.gender_2 = QtWidgets.QComboBox(self.tab)
        self.gender_2.setGeometry(QtCore.QRect(70, 170, 661, 41))
        self.gender_2.setObjectName("gender_2")
        self.gender_2.addItem("")
        self.gender_2.addItem("")
        self.gender_2.addItem("")
        self.fname_2 = QtWidgets.QLineEdit(self.tab)
        self.fname_2.setGeometry(QtCore.QRect(70, 230, 661, 41))
        self.fname_2.setDragEnabled(True)
        self.fname_2.setClearButtonEnabled(True)
        self.fname_2.setObjectName("fname_2")
        self.lname_2 = QtWidgets.QLineEdit(self.tab)
        self.lname_2.setGeometry(QtCore.QRect(70, 290, 661, 41))
        self.lname_2.setDragEnabled(True)
        self.lname_2.setClearButtonEnabled(True)
        self.lname_2.setObjectName("lname_2")
        self.birthday_2 = QtWidgets.QDateEdit(self.tab)
        self.birthday_2.setGeometry(QtCore.QRect(250, 350, 481, 31))
        self.birthday_2.setSpecialValueText("")
        self.birthday_2.setObjectName("birthday_2")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(70, 350, 111, 31))
        self.label_8.setStyleSheet("\n"
"font: 14pt \"Berlin Sans FB\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(70, 400, 171, 31))
        self.label_9.setStyleSheet("\n"
"font: 14pt \"Berlin Sans FB\";")
        self.label_9.setObjectName("label_9")
        self.date_of_entry_2 = QtWidgets.QDateEdit(self.tab)
        self.date_of_entry_2.setGeometry(QtCore.QRect(250, 400, 481, 31))
        self.date_of_entry_2.setSpecialValueText("")
        self.date_of_entry_2.setObjectName("date_of_entry_2")
        self.personal_number_2 = QtWidgets.QLineEdit(self.tab)
        self.personal_number_2.setGeometry(QtCore.QRect(70, 450, 661, 41))
        self.personal_number_2.setDragEnabled(True)
        self.personal_number_2.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.personal_number_2.setClearButtonEnabled(True)
        self.personal_number_2.setObjectName("personal_number_2")
        self.employee_group_2 = QtWidgets.QLineEdit(self.tab)
        self.employee_group_2.setGeometry(QtCore.QRect(70, 510, 661, 41))
        self.employee_group_2.setDragEnabled(True)
        self.employee_group_2.setClearButtonEnabled(True)
        self.employee_group_2.setObjectName("employee_group_2")
        self.hr_level_2 = QtWidgets.QLineEdit(self.tab)
        self.hr_level_2.setGeometry(QtCore.QRect(70, 570, 661, 41))
        self.hr_level_2.setDragEnabled(True)
        self.hr_level_2.setClearButtonEnabled(True)
        self.hr_level_2.setObjectName("hr_level_2")
        self.employement_type_2 = QtWidgets.QLineEdit(self.tab)
        self.employement_type_2.setGeometry(QtCore.QRect(70, 630, 661, 41))
        self.employement_type_2.setDragEnabled(True)
        self.employement_type_2.setClearButtonEnabled(True)
        self.employement_type_2.setObjectName("employement_type_2")
        self.email_2 = QtWidgets.QLineEdit(self.tab)
        self.email_2.setGeometry(QtCore.QRect(70, 690, 661, 41))
        self.email_2.setDragEnabled(True)
        self.email_2.setClearButtonEnabled(True)
        self.email_2.setObjectName("email_2")
        self.report_2 = QtWidgets.QLineEdit(self.tab)
        self.report_2.setGeometry(QtCore.QRect(70, 750, 661, 41))
        self.report_2.setDragEnabled(True)
        self.report_2.setClearButtonEnabled(True)
        self.report_2.setObjectName("report_2")
        self.current_position_2 = QtWidgets.QLineEdit(self.tab)
        self.current_position_2.setGeometry(QtCore.QRect(70, 810, 661, 41))
        self.current_position_2.setDragEnabled(True)
        self.current_position_2.setClearButtonEnabled(True)
        self.current_position_2.setObjectName("current_position_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(70, 890, 271, 51))
        self.pushButton_5.setStyleSheet("background-color: rgb(0, 71, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;")
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(460, 890, 271, 51))
        self.pushButton_6.setStyleSheet("background-color: rgb(0, 0, 118);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;")
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.line_11 = QtWidgets.QFrame(self.tab)
        self.line_11.setGeometry(QtCore.QRect(40, 870, 721, 16))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.tab)
        self.line_12.setGeometry(QtCore.QRect(40, 950, 721, 16))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_2.addWidget(self.widget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1038, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
#------------------------------------- Functionality Mod End----------------------------------------#
        self.pushButton_3.clicked.connect(self.saveInformation)
        self.pushButton_4.clicked.connect(self.clear)
        self.pushButton_5.clicked.connect(self.update)
        self.pushButton_6.clicked.connect(self.clear)
        self.saveButton.clicked.connect(self.reports)
#------------------------------------- Functionality Mod End----------------------------------------#
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setPlaceholderText(_translate("MainWindow", "Title.."))
        self.spacing.setPlaceholderText(_translate("MainWindow", "Spacing.."))
        self.label.setText(_translate("MainWindow", "From:"))
        self.label_2.setText(_translate("MainWindow", "To:"))
        self.saveButton.setText(_translate("MainWindow", "Save Reports"))
        self.openButton.setText(_translate("MainWindow", "Open Reports"))
        self.label_3.setText(_translate("MainWindow", "Please Enter The Following"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Reports), _translate("MainWindow", "Reports "))
        self.label_4.setText(_translate("MainWindow", "Please Enter The Following"))
        self.kim.setPlaceholderText(_translate("MainWindow", "1. KIM"))
        self.lname.setPlaceholderText(_translate("MainWindow", "4. Last Name"))
        self.fname.setPlaceholderText(_translate("MainWindow", "3. First Name "))
        self.gender.setItemText(0, _translate("MainWindow", "2. Gender"))
        self.gender.setItemText(1, _translate("MainWindow", "Male"))
        self.gender.setItemText(2, _translate("MainWindow", "Female"))
        self.employee_group.setPlaceholderText(_translate("MainWindow", "8. Employee Group"))
        self.personal_number.setPlaceholderText(_translate("MainWindow", "7. Personal Number"))
        self.label_5.setText(_translate("MainWindow", "5. Birthday:"))
        self.label_6.setText(_translate("MainWindow", "6. Date of Entry:"))
        self.report.setPlaceholderText(_translate("MainWindow", "12. Report To KIM"))
        self.email.setPlaceholderText(_translate("MainWindow", "11. SMTP Email-Address"))
        self.employement_type.setPlaceholderText(_translate("MainWindow", "10. Employement Type"))
        self.hr_level.setPlaceholderText(_translate("MainWindow", "9. HR Executive Level "))
        self.current_position.setPlaceholderText(_translate("MainWindow", "13. Current Position Title"))
        self.pushButton_3.setText(_translate("MainWindow", "Save "))
        self.pushButton_4.setText(_translate("MainWindow", "Clear Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Add Employee"))
        self.label_7.setText(_translate("MainWindow", "Please Enter The Following"))
        self.kim_2.setPlaceholderText(_translate("MainWindow", " *1. Enter The Employee\'s KIM"))
        self.gender_2.setItemText(0, _translate("MainWindow", "2. Gender"))
        self.gender_2.setItemText(1, _translate("MainWindow", "Male"))
        self.gender_2.setItemText(2, _translate("MainWindow", "Female"))
        self.fname_2.setPlaceholderText(_translate("MainWindow", "3. First Name "))
        self.lname_2.setPlaceholderText(_translate("MainWindow", "4. Last Name"))
        self.label_8.setText(_translate("MainWindow", "5. Birthday:"))
        self.label_9.setText(_translate("MainWindow", "6. Date of Entry:"))
        self.personal_number_2.setPlaceholderText(_translate("MainWindow", "7. Personal Number"))
        self.employee_group_2.setPlaceholderText(_translate("MainWindow", "8. Employee Group"))
        self.hr_level_2.setPlaceholderText(_translate("MainWindow", "9. HR Executive Level "))
        self.employement_type_2.setPlaceholderText(_translate("MainWindow", "10. Employement Type"))
        self.email_2.setPlaceholderText(_translate("MainWindow", "11. SMTP Email-Address"))
        self.report_2.setPlaceholderText(_translate("MainWindow", "12. Report To KIM"))
        self.current_position_2.setPlaceholderText(_translate("MainWindow", "13. Current Position Title"))
        self.pushButton_5.setText(_translate("MainWindow", "Update"))
        self.pushButton_6.setText(_translate("MainWindow", "Clear Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Update Employee"))
    
    def update(self):
            kim = 0
            kim = str(self.kim_2.text())
            
            if find_employee(kim) ==1:
                data = {
                'kim': self.kim_2.text(),
                'gender':self.gender_2.currentData() ,
                'fname':self.fname_2.text(),
                'lname':self.lname_2.text(),
                'birthday':self.birthday_2.text(),
                'date_of_entry':self.birthday_2.text(),
                'personal_number':self.personal_number_2.text(),
                'employee_group':self.employee_group_2.text(),
                'hr_level':self.hr_level_2.text(),
                'email':self.email_2.text(),
                'report':self.report_2.text(),
                'current_position':self.current_position_2.text()
                }
                if updateInfo(data) == 1:
                        return QtWidgets.QMessageBox.about(self.tabWidget,'Success','Employee Information Updated Successfully')
                else:
                         return QtWidgets.QMessageBox.about(self.tabWidget,'Error','Information Could Not Be Saved')
            else:
                return QtWidgets.QMessageBox.about(self.tabWidget,'Error','Could Not Find Employee')
#---------------------------------------------------------------------------------------------------------------------
    def clear(self):
            #loadInfo()
            self.kim.clear()
            self.fname.clear()
            self.lname.clear()
            self.birthday.clear()
            self.personal_number.clear()
            self.employee_group.clear()
            self.personal_number.clear()
            self.employee_group.clear()
            self.hr_level.clear()
            self.email.clear()
            self.report.clear()
            self.current_position.clear()
    def saveInformation(self):
                if self.gender.currentText() =='Male':
                        gender =1
                else:
                        gender = 0
                data = {
                'kim': self.kim.text(),
                'gender':gender,
                'fname':self.fname.text(),
                'lname':self.lname.text(),
                'bdate':self.birthday.text(),
                'date_of_entry':self.birthday.text(),
                'personal_number':self.personal_number.text(),
                'employee_group':self.employee_group.text(),
                'etype':self.employement_type.text(),
                'hr_level':self.hr_level.text(),
                'temail':self.email.text(),
                'report':self.report.text(),
                'position':self.current_position.text()
                }
                if saveInfo(data) ==1:
                        return QtWidgets.QMessageBox.about(self.tabWidget,'Success','Employee Information Saved Successfully')
                else:
                       return QtWidgets.QMessageBox.about(self.tabWidget,'Error','Information Could Not Be Saved')
#---------------------------------------------------------------------------------------------------------------------
    def reports(self):
            date1 = str(self.to.text()).split('/')
            to2 = dateCheck('to',date1)
            print(to2)
            date2 = str(self.ffrom.text()).split('/') 
            from2 = dateCheck('fromm',date2)
            print(from2)
            data= {
                'title':self.title.text(),   
                'from':from2,
                'to':to2,
                'spacing':int(0), 
            }
            print(data)
            try:    
                    if gen(generate_report(data.get('from'),data.get('to')),data.get('title'),data.get('spacing')) !=0:
                        return QtWidgets.QMessageBox.about(self.tabWidget,'Success','Report Generated Saved Successfully')
                    else:
                        return QtWidgets.QMessageBox.about(self.tabWidget,'Error','No Data Was Saved During This Period')                            
            except Exception as e:
                    return QtWidgets.QMessageBox.about(self.tabWidget,'Error',e)
                    
#---------------------------------------------------------------------------------------------------------------------
